# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_requests', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
